# base image
FROM node:10.15

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json /app/package.json
COPY nodemon.json /app/nodemon.json
RUN npm install --no-optional
RUN npm install -g @angular/cli@7.3.9

# add app
COPY . /app

# start app
CMD npm start
# CMD ng serve --host 0.0.0.0
# RUN npm run server.run
