FROM node:10.15

WORKDIR /home/node/angular-express

# NB: Only copy files that are required by 'npm install'
# The 'src' directory will be mounted as a shared volume by docker-compose (allowing for live-reload)
COPY package.json .
COPY package-lock.json .
COPY angular.json .
COPY nodemon.json .
COPY tsconfig.json .
COPY tslint.json .
COPY .docker/rm.optional.deps.js ./.docker/rm.optional.deps.js

# before switching to non-root user, change ownership of home
RUN chown -R node:node .
USER node

# NB: this is a workaround due to the fact that npm '--no-optional' flag doesn't work (open script below for more)
RUN node .docker/rm.optional.deps.js

RUN npm install --no-optional
